import type { QuestionnaireSchema } from './types';

export const manufacturingSchema: QuestionnaireSchema = {
  id: 'manufacturing-lead-capture',
  version: '1.0.0',
  entryStepId: 'company_name',
  steps: [
    // SECTION 0: Company Information (30 seconds)
    {
      id: 'company_name',
      kind: 'input',
      title: 'Company Name',
      description: "Enter your company's legal business name",
      required: true,
      type: 'text',
      placeholder: 'Company Inc.',
      transitions: { fallbackNextStepId: 'ma_zipcodes' },
    },
    // SECTION 1: Geographic Footprint Analysis (30 seconds)
    {
      id: 'ma_zipcodes',
      kind: 'ziplist',
      title: 'Primary Manufacturing Facility Locations (ZIP Codes)',
      description: 'Enter ZIP codes for your manufacturing plants. We\'ll assess location-specific risks including power reliability and supply chain vulnerabilities.',
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'company_revenue' },
    },
    {
      id: 'company_revenue',
      kind: 'single',
      title: 'Company Annual Revenue',
      description: 'Select your company\'s approximate annual revenue (USD). This helps us scale the assessment complexity and identify appropriate risk management solutions for your organization\'s size.',
      options: [
        { id: 'rev_u10', label: 'Under $10M' },
        { id: 'rev_10_50', label: '$10M - $50M' },
        { id: 'rev_50_100', label: '$50M - $100M' },
        { id: 'rev_100_500', label: '$100M - $500M' },
        { id: 'rev_500_1b', label: '$500M - $1B' },
        { id: 'rev_o1b', label: 'Over $1B' },
      ],
      transitions: { fallbackNextStepId: 'ma_criticality' },
    },
    {
      id: 'ma_criticality',
      kind: 'single',
      title: 'Facility Criticality Distribution',
      description: 'How is production capacity distributed? Single points of failure increase weather risk.',
      options: [
        { id: 'ma_crit_single', label: 'Single critical facility' },
        { id: 'ma_crit_primary', label: 'One primary, multiple secondary' },
        { id: 'ma_crit_equal', label: 'Multiple equally critical sites' },
        { id: 'ma_crit_redundant', label: 'Distributed with full redundancy' },
        { id: 'ma_crit_global', label: 'Global manufacturing network' },
      ],
      transitions: { fallbackNextStepId: 'ma_production_type' },
    },

    // SECTION 2: Manufacturing Operations Profile (45 seconds)
    {
      id: 'ma_production_type',
      kind: 'single',
      title: 'Production Type & Sensitivity',
      description: 'Your production model determines how weather disruptions cascade through operations.',
      options: [
        { id: 'ma_prod_continuous', label: 'Continuous process (24/7, cannot stop)' },
        { id: 'ma_prod_batch', label: 'Batch process (flexible timing)' },
        { id: 'ma_prod_jit', label: 'Just-in-time assembly' },
        { id: 'ma_prod_seasonal', label: 'Seasonal production cycles' },
        { id: 'ma_prod_mixed', label: 'Mixed production types' },
      ],
      transitions: { fallbackNextStepId: 'ma_input_dependencies' },
    },
    {
      id: 'ma_input_dependencies',
      kind: 'multi',
      title: 'Critical Input Dependencies',
      description: 'Which inputs, if disrupted by weather, would halt production? Select all critical dependencies.',
      options: [
        { id: 'ma_input_materials', label: 'Raw materials (weather-sensitive delivery)' },
        { id: 'ma_input_power', label: 'Power (high consumption >10MW)' },
        { id: 'ma_input_water', label: 'Water (process/cooling requirements)' },
        { id: 'ma_input_gas', label: 'Natural gas (process heat)' },
        { id: 'ma_input_multiple', label: 'Multiple critical inputs' },
      ],
      transitions: { fallbackNextStepId: 'ma_product_storage' },
    },
    {
      id: 'ma_product_storage',
      kind: 'single',
      title: 'Product Perishability/Storage',
      description: 'How long can finished products be stored? Limited storage increases weather vulnerability.',
      options: [
        { id: 'ma_stor_immediate', label: 'Immediate shipment required' },
        { id: 'ma_stor_7d', label: '<7 days storage capacity' },
        { id: 'ma_stor_30d', label: '7-30 days storage capacity' },
        { id: 'ma_stor_90d', label: '30-90 days storage capacity' },
        { id: 'ma_stor_90plus', label: '90 days or non-perishable' },
      ],
      transitions: { fallbackNextStepId: 'ma_temp_requirements' },
    },
    {
      id: 'ma_temp_requirements',
      kind: 'single',
      title: 'Quality Control Temperature Requirements',
      description: 'How sensitive are your products/processes to temperature variation? Tighter controls mean higher weather risk.',
      options: [
        { id: 'ma_temp_strict', label: 'Strict control required (±5°F)' },
        { id: 'ma_temp_moderate', label: 'Moderate control (±15°F)' },
        { id: 'ma_temp_broad', label: 'Broad range acceptable (±30°F)' },
        { id: 'ma_temp_insensitive', label: 'Temperature insensitive' },
        { id: 'ma_temp_varies', label: 'Varies by product line' },
      ],
      transitions: { fallbackNextStepId: 'ma_hist_disruptions' },
    },

    // SECTION 3: Weather-Related Production Impact (45 seconds)
    {
      id: 'ma_hist_disruptions',
      kind: 'single',
      title: 'Historical Weather Disruptions (5 Years)',
      description: 'How many weather-related production disruptions have you experienced? Past frequency predicts future risk.',
      options: [
        { id: 'ma_hist_none', label: 'No significant disruptions' },
        { id: 'ma_hist_1_3', label: '1-3 partial shutdowns' },
        { id: 'ma_hist_4_10', label: '4-10 partial shutdowns' },
        { id: 'ma_hist_10plus', label: '>10 partial shutdowns' },
        { id: 'ma_hist_major', label: 'Major shutdown >1 week' },
      ],
      transitions: { fallbackNextStepId: 'ma_power_reliability' },
    },
    {
      id: 'ma_power_reliability',
      kind: 'single',
      title: 'Power Grid Reliability Issues',
      description: 'How often do weather-related power issues affect production? Grid vulnerability is a key risk factor.',
      options: [
        { id: 'ma_power_never', label: 'Never experienced outages' },
        { id: 'ma_power_rare', label: 'Rare outages (<2 per year)' },
        { id: 'ma_power_occasional', label: 'Occasional outages (2-6 per year)' },
        { id: 'ma_power_frequent', label: 'Frequent outages (>6 per year)' },
        { id: 'ma_power_critical', label: 'Critical ongoing issue' },
      ],
      transitions: { fallbackNextStepId: 'ma_supply_vulnerability' },
    },
    {
      id: 'ma_supply_vulnerability',
      kind: 'single',
      title: 'Supply Chain Weather Vulnerability',
      description: 'How vulnerable is your supply chain to weather disruptions? Geographic concentration increases risk.',
      options: [
        { id: 'ma_supply_single', label: 'Single-source critical suppliers' },
        { id: 'ma_supply_regional', label: 'Regional supplier concentration' },
        { id: 'ma_supply_national', label: 'National supplier diversity' },
        { id: 'ma_supply_global', label: 'Global supply chain' },
        { id: 'ma_supply_integrated', label: 'Fully integrated/vertical' },
      ],
      transitions: { fallbackNextStepId: 'ma_production_flexibility' },
    },

    // SECTION 4: Operational Resilience & Protection (45 seconds)
    {
      id: 'ma_production_flexibility',
      kind: 'single',
      title: 'Production Flexibility & Redundancy',
      description: 'Can production shift to other facilities if one is impacted? Flexibility reduces weather risk.',
      options: [
        { id: 'ma_flex_none', label: 'No backup production capability' },
        { id: 'ma_flex_limited', label: 'Limited backup (<25% capacity)' },
        { id: 'ma_flex_moderate', label: 'Moderate backup (25-50% capacity)' },
        { id: 'ma_flex_substantial', label: 'Substantial backup (50-75% capacity)' },
        { id: 'ma_flex_full', label: 'Full redundancy available' },
      ],
      transitions: { fallbackNextStepId: 'ma_inventory_strategy' },
    },
    {
      id: 'ma_inventory_strategy',
      kind: 'single',
      title: 'Inventory Management Strategy',
      description: 'How much buffer inventory do you maintain? Greater buffers provide weather resilience.',
      options: [
        { id: 'ma_inv_jit', label: 'Pure just-in-time (no buffer)' },
        { id: 'ma_inv_minimal', label: 'Minimal buffer (1-3 days)' },
        { id: 'ma_inv_standard', label: 'Standard buffer (1-2 weeks)' },
        { id: 'ma_inv_conservative', label: 'Conservative buffer (2-4 weeks)' },
        { id: 'ma_inv_strategic', label: 'Strategic reserves (>1 month)' },
      ],
      transitions: { fallbackNextStepId: 'ma_financial_strategy' },
    },
    {
      id: 'ma_financial_strategy',
      kind: 'single',
      title: 'Current Weather Risk Financial Strategy',
      description: 'How do you manage weather-related financial risks to production?',
      options: [
        { id: 'ma_fin_traditional', label: 'Traditional financial protection only' },
        { id: 'ma_fin_enhanced', label: 'Enhanced weather-specific financial instruments' },
        { id: 'ma_fin_supply_chain', label: 'Supply chain financial protection included' },
        { id: 'ma_fin_parametric', label: 'Parametric solutions employed' },
        { id: 'ma_fin_comprehensive', label: 'Comprehensive risk financing approach' },
      ],
      transitions: { fallbackNextStepId: 'ma_loss_exposure' },
    },
    {
      id: 'ma_loss_exposure',
      kind: 'single',
      title: 'Annual Weather-Related Loss Exposure',
      description: 'Total annual impact from weather (production losses, expedited shipping, overtime, etc.)?',
      options: [
        { id: 'ma_loss_u2m', label: 'Under $2M' },
        { id: 'ma_loss_2_10m', label: '$2M - $10M' },
        { id: 'ma_loss_10_50m', label: '$10M - $50M' },
        { id: 'ma_loss_50_200m', label: '$50M - $200M' },
        { id: 'ma_loss_o200m', label: 'Over $200M' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // SECTION 5: Contact Information (30 seconds)
    {
      id: 'contact_name',
      kind: 'input',
      title: 'Your Name',
      required: true,
      type: 'text',
      placeholder: 'John Smith',
      transitions: { fallbackNextStepId: 'contact_role' },
    },
    {
      id: 'contact_role',
      kind: 'single',
      title: 'Your Role',
      options: [
        { id: 'role_csuite', label: 'C-Suite Executive' },
        { id: 'role_vp_ops', label: 'VP/Director of Operations' },
        { id: 'role_risk', label: 'Risk Management' },
        { id: 'role_finance', label: 'Finance/Treasury' },
        { id: 'role_facilities', label: 'Facilities Management' },
        { id: 'role_other', label: 'Other' },
      ],
      transitions: { fallbackNextStepId: 'contact_email' },
    },
    {
      id: 'contact_email',
      kind: 'input',
      title: 'Business Email',
      required: true,
      type: 'email',
      placeholder: 'john.smith@company.com',
      transitions: { fallbackNextStepId: 'contact_phone' },
    },
    {
      id: 'contact_phone',
      kind: 'input',
      title: 'Phone Number',
      description: 'For priority assessment delivery',
      required: false,
      type: 'tel',
      placeholder: '(555) 123-4567',
      transitions: { fallbackNextStepId: 'contact_consent' },
    },
    {
      id: 'contact_consent',
      kind: 'multi',
      title: 'Consent & Disclaimer',
      description: '© 2025 Sentinel Shield - Texas Climate Risk Intelligence. This is an educational service only. We are not licensed insurance professionals and do not provide insurance advice.',
      required: true,
      minSelections: 3,
      options: [
        { id: 'consent_educational', label: 'I understand this is an educational climate risk analysis only. Sentinel Shield does not provide insurance advice or sell insurance products. This assessment is for informational purposes only.' },
        { id: 'consent_email', label: 'I consent to receive my Climate Vulnerability Analysis report via email.' },
        { id: 'consent_agg', label: 'I understand that Sentinel Shield may share aggregated, anonymized climate risk data for research purposes.' },
      ],
      transitions: { fallbackNextStepId: 'thank_you' },
    },
    {
      id: 'thank_you',
      kind: 'single',
      title: 'Thank You!',
      description: 'Your Manufacturing Climate Vulnerability Assessment has been submitted successfully. You will receive your personalized analysis report via email within 24-48 hours.',
      options: [
        { id: 'thank_acknowledged', label: 'Assessment Complete' }
      ],
      transitions: { fallbackNextStepId: null },
    },
  ],
  rules: [
    // Pas de règles de branchement nécessaires - flux linéaire pour manufacturing uniquement
  ],
};
