import type { QuestionnaireSchema } from './types';

// Schéma de démonstration minimal. On remplacera par tes questions.
// Démo initiale simplifiée basée sur la Section 0 (pré-qualification)
export const demoSchema: QuestionnaireSchema = {
  id: 'lead-capture',
  version: '0.2.1',
  entryStepId: 'company_name',
  steps: [
    {
      id: 'company_name',
      kind: 'input',
      title: 'Company Name',
      description: "Enter your company's legal business name",
      required: true,
      type: 'text',
      placeholder: 'Company Inc.',
      transitions: { fallbackNextStepId: 'company_revenue' },
    },
    {
      id: 'company_revenue',
      kind: 'single',
      title: 'Company Annual Revenue',
      description: "Select your company's approximate annual revenue (USD).",
      options: [
        { id: 'rev_u10', label: 'Under $10M' },
        { id: 'rev_10_50', label: '$10M - $50M' },
        { id: 'rev_50_100', label: '$50M - $100M' },
        { id: 'rev_100_500', label: '$100M - $500M' },
        { id: 'rev_500_1b', label: '$500M - $1B' },
        { id: 'rev_o1b', label: 'Over $1B' },
      ],
      transitions: { fallbackNextStepId: 'primary_industry' },
    },
    {
      id: 'primary_industry',
      kind: 'single',
      title: 'Primary Industry',
      description: 'Select the industry that best describes your primary business operations.',
      required: true,
      options: [
        { id: 'ind_energy', label: 'Energy & Utilities' },
        { id: 'ind_petrochem', label: 'Petrochemical & Refining' },
        { id: 'ind_logistics', label: 'Logistics & Transportation' },
        { id: 'ind_manufacturing', label: 'Manufacturing' },
        { id: 'ind_construction', label: 'Construction & Infrastructure' },
        { id: 'ind_other', label: 'Other' },
      ],
    },

    // ENERGY branch intro (ZIP list + quelques questions de base)
    {
      id: 'en_zipcodes',
      kind: 'ziplist',
      title: 'Primary Operating Locations (ZIP Codes)',
      description: 'Enter up to 5 ZIP codes. Primary location required.',
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'en_asset_concentration' },
    },
    {
      id: 'en_asset_concentration',
      kind: 'single',
      title: 'Asset Concentration by Location',
      options: [
        { id: 'en_conc_high75', label: 'Highly concentrated (>75% in one location)' },
        { id: 'en_conc_50_75', label: 'Concentrated (50-75% in one location)' },
        { id: 'en_conc_25_50', label: 'Moderately distributed (25-50% across 2-3 locations)' },
        { id: 'en_conc_well', label: 'Well distributed (<25% in any single location, 4-5 locations)' },
        { id: 'en_conc_high_dist', label: 'Highly distributed (<15% in any location, >5 locations)' },
      ],
      transitions: { fallbackNextStepId: 'en_infra_type' },
    },

    // Energy Section 2: Operations Profile
    {
      id: 'en_infra_type',
      kind: 'single',
      title: 'Primary Energy Infrastructure Type',
      options: [
        { id: 'en_gen_plants', label: 'Power Generation Plants' },
        { id: 'en_tnd_networks', label: 'Transmission & Distribution Networks' },
        { id: 'en_oil_gas_prod', label: 'Oil & Gas Production Facilities' },
        { id: 'en_pipelines', label: 'Pipeline Systems' },
        { id: 'en_renewables', label: 'Renewable Energy Farms (Solar/Wind)' },
        { id: 'en_storage', label: 'Energy Storage Facilities' },
        { id: 'en_mixed', label: 'Mixed Portfolio' },
      ],
      transitions: { fallbackNextStepId: 'en_capacity' },
    },
    {
      id: 'en_capacity',
      kind: 'single',
      title: 'Critical Generation/Production Capacity',
      options: [
        { id: 'en_cap_u100', label: 'Under 100 MW / 10,000 BBL/day' },
        { id: 'en_cap_100_500', label: '100-500 MW / 10,000-50,000 BBL/day' },
        { id: 'en_cap_500_1000', label: '500-1,000 MW / 50,000-100,000 BBL/day' },
        { id: 'en_cap_1000_5000', label: '1,000-5,000 MW / 100,000-500,000 BBL/day' },
        { id: 'en_cap_o5000', label: 'Over 5,000 MW / 500,000 BBL/day' },
      ],
      transitions: { fallbackNextStepId: 'en_grid_dependency' },
    },
    {
      id: 'en_grid_dependency',
      kind: 'single',
      title: 'Grid/Network Dependencies',
      options: [
        { id: 'en_dep_standalone', label: 'Standalone operations' },
        { id: 'en_dep_regional', label: 'Regional grid critical node' },
        { id: 'en_dep_interstate', label: 'Interstate/International connector' },
        { id: 'en_dep_multi', label: 'Multiple grid interconnections' },
        { id: 'en_dep_critical', label: 'Critical infrastructure provider' },
      ],
      transitions: { fallbackNextStepId: 'en_temp_sensitivity' },
    },
    {
      id: 'en_temp_sensitivity',
      kind: 'multi',
      title: 'Operational Temperature Sensitivity',
      options: [
        { id: 'en_temp_low20', label: 'Significant output reduction below 20°F' },
        { id: 'en_temp_high95', label: 'Significant output reduction above 95°F' },
        { id: 'en_temp_both', label: 'Both extreme temperatures affect operations' },
        { id: 'en_temp_minimal', label: 'Minimal temperature impact on operations' },
      ],
      transitions: { fallbackNextStepId: 'en_hist_impact' },
    },

    // Energy Section 3: Weather Vulnerability
    {
      id: 'en_hist_impact',
      kind: 'single',
      title: 'Historical Weather Impact (Last 5 Years)',
      options: [
        { id: 'en_hist_shutdown_7d', label: 'Complete shutdown lasting over 7 days' },
        { id: 'en_hist_partial_7d', label: 'Partial shutdown lasting over 7 days' },
        { id: 'en_hist_multiple_brief', label: 'Multiple brief outages (3-5 events per year)' },
        { id: 'en_hist_minor', label: 'Minor disruptions only (1-2 days per year)' },
        { id: 'en_hist_none', label: 'No significant weather impacts' },
      ],
      transitions: { fallbackNextStepId: 'en_peak_season' },
    },
    {
      id: 'en_peak_season',
      kind: 'single',
      title: 'Peak Season Vulnerability',
      options: [
        { id: 'en_peak_summer', label: 'Summer peak (cooling/demand)' },
        { id: 'en_peak_winter', label: 'Winter peak (heating/demand)' },
        { id: 'en_peak_hurricane', label: 'Hurricane season (Aug-Nov)' },
        { id: 'en_peak_year_round', label: 'Year-round equal vulnerability' },
        { id: 'en_peak_minimal', label: 'Minimal seasonal variation' },
      ],
      transitions: { fallbackNextStepId: 'en_supply_chain' },
    },
    {
      id: 'en_supply_chain',
      kind: 'multi',
      title: 'Supply Chain Weather Exposure',
      options: [
        { id: 'en_sc_fuel', label: 'Fuel delivery disruption risk' },
        { id: 'en_sc_transmission', label: 'Transmission line vulnerability' },
        { id: 'en_sc_water', label: 'Water availability for cooling' },
        { id: 'en_sc_renewable_var', label: 'Renewable resource variability' },
        { id: 'en_sc_multiple', label: 'Multiple supply chain risks' },
      ],
      transitions: { fallbackNextStepId: 'en_monitoring' },
    },

    // Energy Section 4: Operational & Financial Preparedness
    {
      id: 'en_monitoring',
      kind: 'single',
      title: 'Current Weather Monitoring Capabilities',
      options: [
        { id: 'en_mon_none', label: 'No dedicated weather monitoring' },
        { id: 'en_mon_basic', label: 'Basic public weather services' },
        { id: 'en_mon_prof', label: 'Professional weather service subscription' },
        { id: 'en_mon_ioc', label: 'Integrated operations center with weather desk' },
        { id: 'en_mon_ai', label: 'Advanced AI/ML predictive systems' },
      ],
      transitions: { fallbackNextStepId: 'en_backup' },
    },
    {
      id: 'en_backup',
      kind: 'single',
      title: 'Backup & Redundancy Systems',
      options: [
        { id: 'en_bu_none', label: 'No backup systems (0% redundancy)' },
        { id: 'en_bu_min', label: 'Minimal backup (<25% capacity)' },
        { id: 'en_bu_mod', label: 'Moderate backup (25-50% capacity)' },
        { id: 'en_bu_sub', label: 'Substantial backup (50-75% capacity)' },
        { id: 'en_bu_near', label: 'Near-complete redundancy (>75% capacity)' },
      ],
      transitions: { fallbackNextStepId: 'en_fin_strategy' },
    },
    {
      id: 'en_fin_strategy',
      kind: 'single',
      title: 'Weather-Related Financial Protection Strategy',
      options: [
        { id: 'en_fin_trad', label: 'Traditional financial instruments only' },
        { id: 'en_fin_explore', label: 'Currently exploring alternative financial solutions' },
        { id: 'en_fin_hybrid', label: 'Hybrid approach combining traditional and modern solutions' },
        { id: 'en_fin_optimized', label: 'Fully optimized multi-layered financial strategy' },
        { id: 'en_fin_self', label: 'Self-managed risk retention program' },
      ],
      transitions: { fallbackNextStepId: 'en_fin_exposure' },
    },
    {
      id: 'en_fin_exposure',
      kind: 'single',
      title: 'Estimated Annual Weather-Related Financial Exposure',
      options: [
        { id: 'en_expo_u1', label: 'Under $1M annually' },
        { id: 'en_expo_1_10', label: '$1M - $10M annually' },
        { id: 'en_expo_10_50', label: '$10M - $50M annually' },
        { id: 'en_expo_50_200', label: '$50M - $200M annually' },
        { id: 'en_expo_o200', label: 'Over $200M annually' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // Petrochemical branch intro (zip + coastal proximity)
    {
      id: 'pe_zipcodes',
      kind: 'ziplist',
      title: 'Primary Facility Locations (ZIP Codes)',
      description: "Enter ZIP codes for refineries, chemical plants, and storage facilities.",
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'pe_coastal' },
    },
    {
      id: 'pe_coastal',
      kind: 'single',
      title: 'Coastal Proximity of Main Facilities',
      options: [
        { id: 'pe_coast_0_5', label: 'Direct waterfront (<0.5 miles from coast)' },
        { id: 'pe_coast_0_5_5', label: 'Near coast (0.5-5 miles from coast)' },
        { id: 'pe_coast_5_25', label: 'Coastal region (5-25 miles from coast)' },
        { id: 'pe_coast_25p', label: 'Inland (>25 miles from any coast)' },
      ],
      transitions: { fallbackNextStepId: 'pe_capacity' },
    },

    // Petrochemical Section 2: Facility & Process Profile
    {
      id: 'pe_capacity',
      kind: 'single',
      title: 'Primary Processing Capacity',
      options: [
        { id: 'pe_cap_u50k', label: 'Under 50,000 BBL/day' },
        { id: 'pe_cap_50_150k', label: '50,000 - 150,000 BBL/day' },
        { id: 'pe_cap_150_300k', label: '150,000 - 300,000 BBL/day' },
        { id: 'pe_cap_300_500k', label: '300,000 - 500,000 BBL/day' },
        { id: 'pe_cap_o500k', label: 'Over 500,000 BBL/day' },
      ],
      transitions: { fallbackNextStepId: 'pe_process_types' },
    },
    {
      id: 'pe_process_types',
      kind: 'multi',
      title: 'Critical Process Types',
      options: [
        { id: 'pe_proc_atm_vac', label: 'Atmospheric/Vacuum Distillation' },
        { id: 'pe_proc_cat', label: 'Catalytic Cracking/Reforming' },
        { id: 'pe_proc_hydro', label: 'Hydrotreating/Hydrocracking' },
        { id: 'pe_proc_alk_iso', label: 'Alkylation/Isomerization' },
        { id: 'pe_proc_integration', label: 'Petrochemical Integration' },
        { id: 'pe_proc_specialty', label: 'Specialty Chemicals' },
      ],
      transitions: { fallbackNextStepId: 'pe_storage_capacity' },
    },
    {
      id: 'pe_storage_capacity',
      kind: 'single',
      title: 'Storage Capacity & Type',
      options: [
        { id: 'pe_storage_u1m', label: 'Under 1M BBL total' },
        { id: 'pe_storage_1_5m', label: '1M - 5M BBL total' },
        { id: 'pe_storage_5_15m', label: '5M - 15M BBL total' },
        { id: 'pe_storage_15_30m', label: '15M - 30M BBL total' },
        { id: 'pe_storage_o30m', label: 'Over 30M BBL total' },
      ],
      transitions: { fallbackNextStepId: 'pe_psm' },
    },
    {
      id: 'pe_psm',
      kind: 'single',
      title: 'Process Safety Management Tier',
      options: [
        { id: 'pe_psm_rmp3', label: 'EPA RMP Program 3 facility' },
        { id: 'pe_psm_rmp2', label: 'EPA RMP Program 2 facility' },
        { id: 'pe_psm_rmp1', label: 'EPA RMP Program 1 facility' },
        { id: 'pe_psm_osha', label: 'OSHA PSM covered only' },
        { id: 'pe_psm_multi', label: 'Multiple tier facilities' },
      ],
      transitions: { fallbackNextStepId: 'pe_temp_thresholds' },
    },

    // Petrochemical Section 3: Weather-Specific Vulnerabilities
    {
      id: 'pe_temp_thresholds',
      kind: 'multi',
      title: 'Critical Temperature Thresholds',
      options: [
        { id: 'pe_temp_lt25', label: 'Below 25°F (freeze protection issues)' },
        { id: 'pe_temp_lt0', label: 'Below 0°F (extreme cold)' },
        { id: 'pe_temp_gt95', label: 'Above 95°F (cooling constraints)' },
        { id: 'pe_temp_gt105', label: 'Above 105°F (extreme heat)' },
        { id: 'pe_temp_multiple', label: 'Multiple temperature sensitivities' },
      ],
      transitions: { fallbackNextStepId: 'pe_water_risks' },
    },
    {
      id: 'pe_water_risks',
      kind: 'multi',
      title: 'Water-Related Vulnerabilities',
      options: [
        { id: 'pe_water_surge', label: 'Storm surge exposure (coastal)' },
        { id: 'pe_water_flood', label: 'River/inland flooding risk' },
        { id: 'pe_water_drought', label: 'Drought/water scarcity for cooling' },
        { id: 'pe_water_waste', label: 'Wastewater discharge restrictions' },
        { id: 'pe_water_multiple', label: 'Multiple water risks' },
      ],
      transitions: { fallbackNextStepId: 'pe_wind_limits' },
    },
    {
      id: 'pe_wind_limits',
      kind: 'single',
      title: 'Wind Speed Operational Limits',
      options: [
        { id: 'pe_wind_40', label: 'Shutdown at >40 mph sustained' },
        { id: 'pe_wind_60', label: 'Shutdown at >60 mph sustained' },
        { id: 'pe_wind_75', label: 'Shutdown at >75 mph sustained' },
        { id: 'pe_wind_100', label: 'Shutdown at >100 mph sustained' },
        { id: 'pe_wind_none', label: 'No wind-related shutdowns' },
      ],
      transitions: { fallbackNextStepId: 'pe_turnaround' },
    },

    // Petrochemical Section 4: Operational Resilience & Protection
    {
      id: 'pe_turnaround',
      kind: 'single',
      title: 'Turnaround/Maintenance Weather Windows',
      options: [
        { id: 'pe_turn_fixed', label: 'Fixed schedule regardless of weather' },
        { id: 'pe_turn_some', label: 'Some weather consideration' },
        { id: 'pe_turn_optimized', label: 'Weather-optimized scheduling' },
        { id: 'pe_turn_flexible', label: 'Fully flexible weather-based planning' },
        { id: 'pe_turn_continuous', label: 'Continuous operations (no turnarounds)' },
      ],
      transitions: { fallbackNextStepId: 'pe_backup_power' },
    },
    {
      id: 'pe_backup_power',
      kind: 'single',
      title: 'Emergency Power Generation',
      options: [
        { id: 'pe_power_none', label: 'No backup power' },
        { id: 'pe_power_crit', label: 'Critical systems only (<24 hours)' },
        { id: 'pe_power_partial', label: 'Partial plant operation (24-72 hours)' },
        { id: 'pe_power_full', label: 'Full operation capability (>72 hours)' },
        { id: 'pe_power_redundant', label: 'Redundant utility feeds' },
      ],
      transitions: { fallbackNextStepId: 'pe_fin_risk' },
    },
    {
      id: 'pe_fin_risk',
      kind: 'single',
      title: 'Current Approach to Weather-Related Financial Risk',
      options: [
        { id: 'pe_fin_standard', label: 'Standard financial protection only' },
        { id: 'pe_fin_enhanced', label: 'Enhanced weather-specific financial instruments' },
        { id: 'pe_fin_internal', label: 'Internal risk retention mechanisms' },
        { id: 'pe_fin_parametric', label: 'Parametric weather solutions in place' },
        { id: 'pe_fin_evaluating', label: 'Actively evaluating alternatives' },
      ],
      transitions: { fallbackNextStepId: 'pe_loss_expectation' },
    },
    {
      id: 'pe_loss_expectation',
      kind: 'single',
      title: 'Annual Weather-Related Loss Expectation',
      options: [
        { id: 'pe_loss_u5', label: 'Under $5M' },
        { id: 'pe_loss_5_25', label: '$5M - $25M' },
        { id: 'pe_loss_25_100', label: '$25M - $100M' },
        { id: 'pe_loss_100_500', label: '$100M - $500M' },
        { id: 'pe_loss_o500', label: 'Over $500M' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // Logistics branch intro
    {
      id: 'lo_zipcodes',
      kind: 'ziplist',
      title: 'Primary Hub/Terminal Locations (ZIP Codes)',
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'lo_network_coverage' },
    },
    {
      id: 'lo_network_coverage',
      kind: 'single',
      title: 'Network Coverage Concentration',
      options: [
        { id: 'lo_single_region', label: 'Single region focus' },
        { id: 'lo_multi_2_3', label: 'Multi-regional (2-3 regions)' },
        { id: 'lo_national', label: 'National coverage' },
        { id: 'lo_na', label: 'North American coverage' },
        { id: 'lo_global', label: 'Global operations' },
      ],
      transitions: { fallbackNextStepId: 'lo_fleet' },
    },
    // Logistics Section 2
    {
      id: 'lo_fleet',
      kind: 'multi',
      title: 'Fleet & Asset Composition',
      options: [
        { id: 'lo_fleet_long', label: 'Long-haul trucking (>500 miles)' },
        { id: 'lo_fleet_regional', label: 'Regional/local delivery (<500 miles)' },
        { id: 'lo_fleet_intermodal', label: 'Intermodal (rail/truck)' },
        { id: 'lo_fleet_ocean', label: 'Ocean/port operations' },
        { id: 'lo_fleet_air', label: 'Air cargo operations' },
        { id: 'lo_fleet_warehouse', label: 'Warehousing/distribution only' },
      ],
      transitions: { fallbackNextStepId: 'lo_corridors' },
    },
    {
      id: 'lo_corridors',
      kind: 'multi',
      title: 'Critical Route Dependencies',
      options: [
        { id: 'lo_c_i10', label: 'I-10 Corridor (Southern)' },
        { id: 'lo_c_i95', label: 'I-95 Corridor (Eastern)' },
        { id: 'lo_c_i5', label: 'I-5 Corridor (Western)' },
        { id: 'lo_c_i80_90', label: 'I-80/90 Corridor (Northern)' },
        { id: 'lo_c_multi', label: 'Multiple critical corridors' },
        { id: 'lo_c_none', label: 'No specific corridor dependency' },
      ],
      transitions: { fallbackNextStepId: 'lo_time_sensitive' },
    },
    {
      id: 'lo_time_sensitive',
      kind: 'single',
      title: 'Time-Sensitive Delivery Percentage',
      options: [
        { id: 'lo_ts_lt10', label: '<10% time-critical shipments' },
        { id: 'lo_ts_10_25', label: '10-25% time-critical' },
        { id: 'lo_ts_25_50', label: '25-50% time-critical' },
        { id: 'lo_ts_50_75', label: '50-75% time-critical' },
        { id: 'lo_ts_75', label: '75% time-critical' },
      ],
      transitions: { fallbackNextStepId: 'lo_penalties' },
    },
    {
      id: 'lo_penalties',
      kind: 'single',
      title: 'Customer Penalty Exposure',
      options: [
        { id: 'lo_pen_none', label: 'No formal SLA penalties' },
        { id: 'lo_pen_u50k', label: 'Under $50K per incident' },
        { id: 'lo_pen_50_250', label: '$50K - $250K per incident' },
        { id: 'lo_pen_250_1m', label: '$250K - $1M per incident' },
        { id: 'lo_pen_o1m', label: 'Over $1M per incident' },
      ],
      transitions: { fallbackNextStepId: 'lo_weather_pattern' },
    },

    // Logistics Section 3
    {
      id: 'lo_weather_pattern',
      kind: 'single',
      title: 'Most Disruptive Weather Pattern',
      options: [
        { id: 'lo_wp_winter', label: 'Winter storms (ice/snow)' },
        { id: 'lo_wp_hurricanes', label: 'Hurricanes/tropical systems' },
        { id: 'lo_wp_flood', label: 'Flooding/washouts' },
        { id: 'lo_wp_heat', label: 'Extreme heat (>100°F)' },
        { id: 'lo_wp_fog', label: 'Fog/visibility issues' },
        { id: 'lo_wp_tornado', label: 'Tornado/severe thunderstorms' },
      ],
      transitions: { fallbackNextStepId: 'lo_annual_delays' },
    },
    {
      id: 'lo_annual_delays',
      kind: 'single',
      title: 'Average Annual Weather Delays',
      options: [
        { id: 'lo_delay_u100', label: 'Under 100 shipment-days' },
        { id: 'lo_delay_100_500', label: '100-500 shipment-days' },
        { id: 'lo_delay_500_2000', label: '500-2,000 shipment-days' },
        { id: 'lo_delay_2000_10000', label: '2,000-10,000 shipment-days' },
        { id: 'lo_delay_o10000', label: 'Over 10,000 shipment-days' },
      ],
      transitions: { fallbackNextStepId: 'lo_alt_routes' },
    },
    {
      id: 'lo_alt_routes',
      kind: 'single',
      title: 'Alternative Route Flexibility',
      options: [
        { id: 'lo_alt_none', label: 'No alternative routes available' },
        { id: 'lo_alt_limited', label: 'Limited alternatives (+50% distance)' },
        { id: 'lo_alt_moderate', label: 'Moderate alternatives (+25% distance)' },
        { id: 'lo_alt_good', label: 'Good alternatives (+10% distance)' },
        { id: 'lo_alt_excellent', label: 'Excellent network redundancy' },
      ],
      transitions: { fallbackNextStepId: 'lo_intelligence' },
    },

    // Logistics Section 4
    {
      id: 'lo_intelligence',
      kind: 'single',
      title: 'Weather Intelligence Integration',
      options: [
        { id: 'lo_int_none', label: 'No systematic weather tracking' },
        { id: 'lo_int_manual', label: 'Manual weather monitoring' },
        { id: 'lo_int_basic', label: 'Basic GPS/weather integration' },
        { id: 'lo_int_advanced', label: 'Advanced route optimization software' },
        { id: 'lo_int_ai', label: 'AI-powered predictive routing' },
      ],
      transitions: { fallbackNextStepId: 'lo_safety' },
    },
    {
      id: 'lo_safety',
      kind: 'single',
      title: 'Driver/Asset Safety Protocols',
      options: [
        { id: 'lo_safety_basic', label: 'Basic weather guidelines' },
        { id: 'lo_safety_thresholds', label: 'Formal shutdown thresholds' },
        { id: 'lo_safety_realtime', label: 'Real-time decision support' },
        { id: 'lo_safety_auto', label: 'Automated safety systems' },
        { id: 'lo_safety_leading', label: 'Industry-leading safety program' },
      ],
      transitions: { fallbackNextStepId: 'lo_fin_protection' },
    },
    {
      id: 'lo_fin_protection',
      kind: 'single',
      title: 'Financial Protection for Weather Disruption',
      options: [
        { id: 'lo_fin_none', label: 'No specific weather-related financial protection' },
        { id: 'lo_fin_basic', label: 'Basic business continuity funding' },
        { id: 'lo_fin_contingent', label: 'Enhanced contingent financial arrangements' },
        { id: 'lo_fin_parametric', label: 'Parametric weather triggers utilized' },
        { id: 'lo_fin_comprehensive', label: 'Comprehensive multi-layer financial approach' },
      ],
      transitions: { fallbackNextStepId: 'lo_revenue_impact' },
    },
    {
      id: 'lo_revenue_impact',
      kind: 'single',
      title: 'Annual Weather-Related Revenue Impact',
      options: [
        { id: 'lo_rev_u500k', label: 'Under $500K' },
        { id: 'lo_rev_500k_2m', label: '$500K - $2M' },
        { id: 'lo_rev_2_10m', label: '$2M - $10M' },
        { id: 'lo_rev_10_50m', label: '$10M - $50M' },
        { id: 'lo_rev_o50m', label: 'Over $50M' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // Manufacturing branch intro
    {
      id: 'ma_zipcodes',
      kind: 'ziplist',
      title: 'Primary Manufacturing Facility Locations (ZIP Codes)',
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'ma_criticality' },
    },
    {
      id: 'ma_criticality',
      kind: 'single',
      title: 'Facility Criticality Distribution',
      options: [
        { id: 'ma_single', label: 'Single critical facility' },
        { id: 'ma_one_primary', label: 'One primary, multiple secondary' },
        { id: 'ma_multiple_equal', label: 'Multiple equally critical sites' },
        { id: 'ma_distributed', label: 'Distributed with full redundancy' },
        { id: 'ma_global', label: 'Global manufacturing network' },
      ],
      transitions: { fallbackNextStepId: 'ma_production_type' },
    },
    // Manufacturing Section 2
    {
      id: 'ma_production_type',
      kind: 'single',
      title: 'Production Type & Sensitivity',
      options: [
        { id: 'ma_prod_continuous', label: 'Continuous process (24/7, cannot stop)' },
        { id: 'ma_prod_batch', label: 'Batch process (flexible timing)' },
        { id: 'ma_prod_jit', label: 'Just-in-time assembly' },
        { id: 'ma_prod_seasonal', label: 'Seasonal production cycles' },
        { id: 'ma_prod_mixed', label: 'Mixed production types' },
      ],
      transitions: { fallbackNextStepId: 'ma_inputs' },
    },
    {
      id: 'ma_inputs',
      kind: 'multi',
      title: 'Critical Input Dependencies',
      options: [
        { id: 'ma_in_raw', label: 'Raw materials (weather-sensitive delivery)' },
        { id: 'ma_in_power', label: 'Power (high consumption >10MW)' },
        { id: 'ma_in_water', label: 'Water (process/cooling requirements)' },
        { id: 'ma_in_gas', label: 'Natural gas (process heat)' },
        { id: 'ma_in_multiple', label: 'Multiple critical inputs' },
      ],
      transitions: { fallbackNextStepId: 'ma_perishability' },
    },
    {
      id: 'ma_perishability',
      kind: 'single',
      title: 'Product Perishability/Storage',
      options: [
        { id: 'ma_store_immediate', label: 'Immediate shipment required' },
        { id: 'ma_store_lt7', label: '<7 days storage capacity' },
        { id: 'ma_store_7_30', label: '7-30 days storage capacity' },
        { id: 'ma_store_30_90', label: '30-90 days storage capacity' },
        { id: 'ma_store_90p', label: '90 days or non-perishable' },
      ],
      transitions: { fallbackNextStepId: 'ma_quality_temp' },
    },
    {
      id: 'ma_quality_temp',
      kind: 'single',
      title: 'Quality Control Temperature Requirements',
      options: [
        { id: 'ma_temp_strict', label: 'Strict control required (±5°F)' },
        { id: 'ma_temp_mod', label: 'Moderate control (±15°F)' },
        { id: 'ma_temp_broad', label: 'Broad range acceptable (±30°F)' },
        { id: 'ma_temp_insensitive', label: 'Temperature insensitive' },
        { id: 'ma_temp_varies', label: 'Varies by product line' },
      ],
      transitions: { fallbackNextStepId: 'ma_hist' },
    },
    // Manufacturing Section 3
    {
      id: 'ma_hist',
      kind: 'single',
      title: 'Historical Weather Disruptions (5 Years)',
      options: [
        { id: 'ma_hist_none', label: 'No significant disruptions' },
        { id: 'ma_hist_1_3', label: '1-3 partial shutdowns' },
        { id: 'ma_hist_4_10', label: '4-10 partial shutdowns' },
        { id: 'ma_hist_10p', label: '10 partial shutdowns' },
        { id: 'ma_hist_major', label: 'Major shutdown >1 week' },
      ],
      transitions: { fallbackNextStepId: 'ma_grid' },
    },
    {
      id: 'ma_grid',
      kind: 'single',
      title: 'Power Grid Reliability Issues',
      options: [
        { id: 'ma_grid_never', label: 'Never experienced outages' },
        { id: 'ma_grid_rare', label: 'Rare outages (<2 per year)' },
        { id: 'ma_grid_occ', label: 'Occasional outages (2-6 per year)' },
        { id: 'ma_grid_freq', label: 'Frequent outages (>6 per year)' },
        { id: 'ma_grid_critical', label: 'Critical ongoing issue' },
      ],
      transitions: { fallbackNextStepId: 'ma_supply_chain' },
    },
    {
      id: 'ma_supply_chain',
      kind: 'single',
      title: 'Supply Chain Weather Vulnerability',
      options: [
        { id: 'ma_sc_single', label: 'Single-source critical suppliers' },
        { id: 'ma_sc_regional', label: 'Regional supplier concentration' },
        { id: 'ma_sc_national', label: 'National supplier diversity' },
        { id: 'ma_sc_global', label: 'Global supply chain' },
        { id: 'ma_sc_vertical', label: 'Fully integrated/vertical' },
      ],
      transitions: { fallbackNextStepId: 'ma_flex' },
    },
    // Manufacturing Section 4
    {
      id: 'ma_flex',
      kind: 'single',
      title: 'Production Flexibility & Redundancy',
      options: [
        { id: 'ma_flex_none', label: 'No backup production capability' },
        { id: 'ma_flex_min', label: 'Limited backup (<25% capacity)' },
        { id: 'ma_flex_mod', label: 'Moderate backup (25-50% capacity)' },
        { id: 'ma_flex_sub', label: 'Substantial backup (50-75% capacity)' },
        { id: 'ma_flex_full', label: 'Full redundancy available' },
      ],
      transitions: { fallbackNextStepId: 'ma_inventory' },
    },
    {
      id: 'ma_inventory',
      kind: 'single',
      title: 'Inventory Management Strategy',
      options: [
        { id: 'ma_inv_jit', label: 'Pure just-in-time (no buffer)' },
        { id: 'ma_inv_min', label: 'Minimal buffer (1-3 days)' },
        { id: 'ma_inv_std', label: 'Standard buffer (1-2 weeks)' },
        { id: 'ma_inv_cons', label: 'Conservative buffer (2-4 weeks)' },
        { id: 'ma_inv_strat', label: 'Strategic reserves (>1 month)' },
      ],
      transitions: { fallbackNextStepId: 'ma_fin_strategy' },
    },
    {
      id: 'ma_fin_strategy',
      kind: 'single',
      title: 'Current Weather Risk Financial Strategy',
      options: [
        { id: 'ma_fin_trad', label: 'Traditional financial protection only' },
        { id: 'ma_fin_enhanced', label: 'Enhanced weather-specific financial instruments' },
        { id: 'ma_fin_supply', label: 'Supply chain financial protection included' },
        { id: 'ma_fin_param', label: 'Parametric solutions employed' },
        { id: 'ma_fin_comp', label: 'Comprehensive risk financing approach' },
      ],
      transitions: { fallbackNextStepId: 'ma_loss_exposure' },
    },
    {
      id: 'ma_loss_exposure',
      kind: 'single',
      title: 'Annual Weather-Related Loss Exposure',
      options: [
        { id: 'ma_loss_u2', label: 'Under $2M' },
        { id: 'ma_loss_2_10', label: '$2M - $10M' },
        { id: 'ma_loss_10_50', label: '$10M - $50M' },
        { id: 'ma_loss_50_200', label: '$50M - $200M' },
        { id: 'ma_loss_o200', label: 'Over $200M' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // Construction branch intro
    {
      id: 'co_zipcodes',
      kind: 'ziplist',
      title: 'Primary Project Locations (ZIP Codes)',
      required: true,
      fields: 5,
      requiredMin: 1,
      labelPrefix: 'ZIP Code',
      transitions: { fallbackNextStepId: 'co_geo_concentration' },
    },
    {
      id: 'co_geo_concentration',
      kind: 'single',
      title: 'Project Geographic Concentration',
      options: [
        { id: 'co_single_metro', label: 'Single metro area' },
        { id: 'co_state_wide', label: 'State-wide presence' },
        { id: 'co_multi_state', label: 'Multi-state regional' },
        { id: 'co_national', label: 'National footprint' },
        { id: 'co_international', label: 'International projects' },
      ],
      transitions: { fallbackNextStepId: 'co_projects' },
    },
    // Construction Section 2
    {
      id: 'co_projects',
      kind: 'multi',
      title: 'Project Type Specialization',
      options: [
        { id: 'co_proj_vertical', label: 'Vertical construction (buildings)' },
        { id: 'co_proj_horizontal', label: 'Horizontal construction (infrastructure)' },
        { id: 'co_proj_marine', label: 'Marine/coastal construction' },
        { id: 'co_proj_industrial', label: 'Industrial/energy construction' },
        { id: 'co_proj_mixed', label: 'Mixed/general contractor' },
      ],
      transitions: { fallbackNextStepId: 'co_duration' },
    },
    {
      id: 'co_duration',
      kind: 'single',
      title: 'Average Project Duration',
      options: [
        { id: 'co_dur_u6', label: 'Under 6 months typical' },
        { id: 'co_dur_6_12', label: '6-12 months typical (full season exposure)' },
        { id: 'co_dur_12_24', label: '12-24 months typical (multi-season exposure)' },
        { id: 'co_dur_24_48', label: '24-48 months typical (complete weather cycles)' },
        { id: 'co_dur_o48', label: 'Over 48 months typical (maximum exposure)' },
      ],
      transitions: { fallbackNextStepId: 'co_weather_pct' },
    },
    {
      id: 'co_weather_pct',
      kind: 'single',
      title: 'Weather-Sensitive Work Percentage',
      options: [
        { id: 'co_ws_lt25', label: '<25% weather-dependent' },
        { id: 'co_ws_25_50', label: '25-50% weather-dependent' },
        { id: 'co_ws_50_75', label: '50-75% weather-dependent' },
        { id: 'co_ws_75', label: '75% weather-dependent' },
        { id: 'co_ws_nearly_all', label: 'Nearly all work weather-exposed' },
      ],
      transitions: { fallbackNextStepId: 'co_critical_windows' },
    },
    {
      id: 'co_critical_windows',
      kind: 'multi',
      title: 'Critical Weather Windows',
      options: [
        { id: 'co_cw_concrete', label: 'Concrete pours/curing' },
        { id: 'co_cw_roofing', label: 'Roofing/envelope work' },
        { id: 'co_cw_crane', label: 'Crane operations' },
        { id: 'co_cw_marine', label: 'Marine/water work' },
        { id: 'co_cw_excavation', label: 'Excavation/earthwork' },
        { id: 'co_cw_multiple', label: 'Multiple critical phases' },
      ],
      transitions: { fallbackNextStepId: 'co_delay_days' },
    },
    // Construction Section 3
    {
      id: 'co_delay_days',
      kind: 'single',
      title: 'Average Annual Weather Delay Days',
      options: [
        { id: 'co_delay_lt10', label: '<10 days total' },
        { id: 'co_delay_10_25', label: '10-25 days' },
        { id: 'co_delay_25_50', label: '25-50 days' },
        { id: 'co_delay_50_100', label: '50-100 days' },
        { id: 'co_delay_100', label: '100 days' },
      ],
      transitions: { fallbackNextStepId: 'co_cost_overruns' },
    },
    {
      id: 'co_cost_overruns',
      kind: 'single',
      title: 'Weather-Related Cost Overruns',
      options: [
        { id: 'co_cost_lt2', label: '<2% typical impact' },
        { id: 'co_cost_2_5', label: '2-5% typical impact' },
        { id: 'co_cost_5_10', label: '5-10% typical impact' },
        { id: 'co_cost_10_20', label: '10-20% typical impact' },
        { id: 'co_cost_20', label: '20% typical impact' },
      ],
      transitions: { fallbackNextStepId: 'co_liquidated' },
    },
    {
      id: 'co_liquidated',
      kind: 'single',
      title: 'Liquidated Damages Exposure',
      options: [
        { id: 'co_ld_none', label: 'No LD clauses typically' },
        { id: 'co_ld_lt10k', label: '<$10K per day typical' },
        { id: 'co_ld_10_50k', label: '$10K-$50K per day' },
        { id: 'co_ld_50_200k', label: '$50K-$200K per day' },
        { id: 'co_ld_200k', label: '$200K per day' },
      ],
      transitions: { fallbackNextStepId: 'co_planning' },
    },
    // Construction Section 4
    {
      id: 'co_planning',
      kind: 'single',
      title: 'Weather Planning Sophistication',
      options: [
        { id: 'co_plan_basic', label: 'Basic weather apps only' },
        { id: 'co_plan_prof', label: 'Professional weather service' },
        { id: 'co_plan_project', label: 'Project-specific forecasting' },
        { id: 'co_plan_integrated', label: 'Integrated scheduling software' },
        { id: 'co_plan_advanced', label: 'Advanced predictive analytics' },
      ],
      transitions: { fallbackNextStepId: 'co_float' },
    },
    {
      id: 'co_float',
      kind: 'single',
      title: 'Schedule Float Management',
      options: [
        { id: 'co_float_none', label: 'No weather float included' },
        { id: 'co_float_5_10', label: '5-10% schedule float' },
        { id: 'co_float_10_20', label: '10-20% schedule float' },
        { id: 'co_float_20_30', label: '20-30% schedule float' },
        { id: 'co_float_30', label: '30% schedule float' },
      ],
      transitions: { fallbackNextStepId: 'co_financial' },
    },
    {
      id: 'co_financial',
      kind: 'single',
      title: 'Weather-Related Financial Protection',
      options: [
        { id: 'co_fin_standard', label: 'Standard project financial protection only' },
        { id: 'co_fin_enhanced', label: 'Enhanced weather-specific financial arrangements' },
        { id: 'co_fin_specific', label: 'Project-specific financial solutions' },
        { id: 'co_fin_parametric', label: 'Parametric weather products utilized' },
        { id: 'co_fin_portfolio', label: 'Portfolio-wide financial optimization' },
      ],
      transitions: { fallbackNextStepId: 'co_annual_impact' },
    },
    {
      id: 'co_annual_impact',
      kind: 'single',
      title: 'Annual Weather-Related Financial Impact',
      options: [
        { id: 'co_impact_u1', label: 'Under $1M' },
        { id: 'co_impact_1_5', label: '$1M - $5M' },
        { id: 'co_impact_5_25', label: '$5M - $25M' },
        { id: 'co_impact_25_100', label: '$25M - $100M' },
        { id: 'co_impact_o100', label: 'Over $100M' },
      ],
      transitions: { fallbackNextStepId: 'contact_name' },
    },

    // Contact section commune (démo: email + nom)
    {
      id: 'contact_name',
      kind: 'input',
      title: 'Your Name',
      required: true,
      placeholder: 'Full name',
      transitions: { fallbackNextStepId: 'contact_role' },
    },
    {
      id: 'contact_role',
      kind: 'single',
      title: 'Your Role',
      options: [
        { id: 'role_csuite', label: 'C-Suite Executive' },
        { id: 'role_ops', label: 'VP/Director of Operations' },
        { id: 'role_risk', label: 'Risk Management' },
        { id: 'role_fin', label: 'Finance/Treasury' },
        { id: 'role_fac', label: 'Facilities Management' },
        { id: 'role_other', label: 'Other' },
      ],
      transitions: { fallbackNextStepId: 'contact_email' },
    },
    {
      id: 'contact_email',
      kind: 'input',
      title: 'Business Email',
      required: true,
      type: 'email',
      placeholder: 'name@company.com',
      transitions: { fallbackNextStepId: 'contact_phone' },
    },
    {
      id: 'contact_phone',
      kind: 'input',
      title: 'Phone Number (optional)',
      required: false,
      type: 'tel',
      placeholder: '(xxx) xxx-xxxx',
      transitions: { fallbackNextStepId: 'contact_consent' },
    },
    {
      id: 'contact_consent',
      kind: 'multi',
      title: 'Consent & Disclaimer',
      description: 'Please confirm educational usage and consent to receive your report by email.',
      options: [
        { id: 'consent_edu', label: 'I understand this is an educational climate risk analysis only.' },
        { id: 'consent_email', label: 'I consent to receive my Climate Vulnerability Analysis report via email.' },
        { id: 'consent_agg', label: 'I understand aggregated, anonymized data may be used for research.' },
      ],
      minSelections: 2,
      transitions: { fallbackNextStepId: null },
    },
  ],
  rules: [
    // Passage depuis primary_industry vers les branches spécifiques
    { when: [{ stepId: 'primary_industry', equals: 'ind_energy' }], nextStepId: 'en_zipcodes', priority: 1 },
    { when: [{ stepId: 'primary_industry', equals: 'ind_petrochem' }], nextStepId: 'pe_zipcodes', priority: 1 },
    { when: [{ stepId: 'primary_industry', equals: 'ind_logistics' }], nextStepId: 'lo_zipcodes', priority: 1 },
    { when: [{ stepId: 'primary_industry', equals: 'ind_manufacturing' }], nextStepId: 'ma_zipcodes', priority: 1 },
    { when: [{ stepId: 'primary_industry', equals: 'ind_construction' }], nextStepId: 'co_zipcodes', priority: 1 },
    { when: [{ stepId: 'primary_industry', equals: 'ind_other' }], nextStepId: 'contact_name', priority: 1 },

    // Pas besoin de règles de fin - les fallbackNextStepId font le travail
  ],
};


